2025-04-23 10:45:48.412 CDT [10524] LOG:  starting PostgreSQL 16.3, compiled by Visual C++ build 1939, 64-bit
2025-04-23 10:45:48.417 CDT [10524] LOG:  listening on IPv6 address "::1", port 5432
2025-04-23 10:45:48.417 CDT [10524] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2025-04-23 10:45:48.487 CDT [6764] LOG:  database system was shut down at 2025-04-23 10:44:19 CDT
2025-04-23 10:45:48.517 CDT [10524] LOG:  database system is ready to accept connections
2025-04-23 10:46:23.397 CDT [11880] FATAL:  role "postgres" does not exist
2025-04-23 10:46:30.677 CDT [17004] FATAL:  role "postgres" does not exist
2025-04-23 10:47:05.637 CDT [20216] FATAL:  role "-d" does not exist
2025-04-23 10:47:21.435 CDT [7496] FATAL:  role "postgres" does not exist
2025-04-23 10:48:26.669 CDT [13316] FATAL:  database "gales" does not exist
2025-04-23 10:49:01.260 CDT [3912] FATAL:  role "postgres" does not exist
2025-04-23 10:50:07.465 CDT [14724] FATAL:  role "postgres" does not exist
2025-04-23 10:50:48.479 CDT [10576] LOG:  checkpoint starting: time
2025-04-23 10:50:52.342 CDT [10576] LOG:  checkpoint complete: wrote 38 buffers (0.2%); 0 WAL file(s) added, 0 removed, 0 recycled; write=3.822 s, sync=0.016 s, total=3.864 s; sync files=11, longest=0.002 s, average=0.002 s; distance=197 kB, estimate=197 kB; lsn=0/15A8C80, redo lsn=0/15A8C48
2025-04-23 10:53:33.098 CDT [19284] FATAL:  database "rapid_refresh" does not exist
2025-04-23 11:08:07.155 CDT [5876] FATAL:  role "postgres" does not exist
2025-04-23 11:08:44.822 CDT [144] FATAL:  database "gales" does not exist
2025-04-23 11:18:18.117 CDT [9652] FATAL:  role "postgres" does not exist
2025-04-23 11:18:27.816 CDT [6420] FATAL:  role "postgres" does not exist
2025-04-23 11:20:38.873 CDT [19724] FATAL:  role "postgres" does not exist
2025-04-23 11:23:02.220 CDT [10524] LOG:  server process (PID 7100) was terminated by exception 0xC000013A
2025-04-23 11:23:02.220 CDT [10524] DETAIL:  Failed process was running: SELECT
	  d.datname as "Name",
	  pg_catalog.pg_get_userbyid(d.datdba) as "Owner",
	  pg_catalog.pg_encoding_to_char(d.encoding) as "Encoding",
	  CASE d.datlocprovider WHEN 'c' THEN 'libc' WHEN 'i' THEN 'icu' END AS "Locale Provider",
	  d.datcollate as "Collate",
	  d.datctype as "Ctype",
	  d.daticulocale as "ICU Locale",
	  d.daticurules as "ICU Rules",
	  pg_catalog.array_to_string(d.datacl, E'\n') AS "Access privileges"
	FROM pg_catalog.pg_database d
	ORDER BY 1;
2025-04-23 11:23:02.220 CDT [10524] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2025-04-23 11:23:02.221 CDT [10524] LOG:  terminating any other active server processes
2025-04-23 11:23:02.234 CDT [10524] LOG:  received fast shutdown request
^C2025-04-23 11:26:45.826 CDT [13464] LOG:  starting PostgreSQL 16.3, compiled by Visual C++ build 1939, 64-bit
2025-04-23 11:26:45.831 CDT [13464] LOG:  listening on IPv6 address "::1", port 5432
2025-04-23 11:26:45.831 CDT [13464] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2025-04-23 11:26:45.884 CDT [8812] LOG:  database system was interrupted; last known up at 2025-04-23 10:50:52 CDT
2025-04-23 11:26:45.959 CDT [8812] LOG:  database system was not properly shut down; automatic recovery in progress
2025-04-23 11:26:45.967 CDT [8812] LOG:  redo starts at 0/15A8C48
2025-04-23 11:26:45.967 CDT [8812] LOG:  invalid record length at 0/15A8D30: expected at least 24, got 0
2025-04-23 11:26:45.968 CDT [8812] LOG:  redo done at 0/15A8CF8 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2025-04-23 11:26:45.976 CDT [17724] LOG:  checkpoint starting: end-of-recovery immediate wait
2025-04-23 11:26:45.994 CDT [17724] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.004 s, sync=0.004 s, total=0.021 s; sync files=2, longest=0.002 s, average=0.002 s; distance=0 kB, estimate=0 kB; lsn=0/15A8D30, redo lsn=0/15A8D30
2025-04-23 11:26:46.017 CDT [13464] LOG:  database system is ready to accept connections
2025-04-23 11:27:10.322 CDT [20220] FATAL:  role "postgres" does not exist
2025-04-23 11:27:16.930 CDT [16996] FATAL:  database "gales" does not exist
2025-04-23 11:29:02.800 CDT [15164] FATAL:  database "rapid_refresh" does not exist
2025-04-23 11:29:15.468 CDT [18008] FATAL:  database "rapid_refresh" does not exist
2025-04-23 11:29:32.736 CDT [10124] ERROR:  syntax error at or near "CREATE" at character 31
2025-04-23 11:29:32.736 CDT [10124] STATEMENT:  CREATE DATABASE rapid_refresh
	CREATE DATABASE rapid_refresh;
2025-04-23 11:31:46.008 CDT [17724] LOG:  checkpoint starting: time
2025-04-23 11:32:37.881 CDT [4820] FATAL:  role "postgres" does not exist
2025-04-23 11:32:46.508 CDT [19680] FATAL:  role "postgres" does not exist
2025-04-23 11:33:04.302 CDT [15104] FATAL:  role "postgres" does not exist
2025-04-23 11:33:32.156 CDT [17724] LOG:  checkpoint complete: wrote 972 buffers (5.9%); 0 WAL file(s) added, 0 removed, 0 recycled; write=105.885 s, sync=0.253 s, total=106.148 s; sync files=300, longest=0.004 s, average=0.001 s; distance=4599 kB, estimate=4599 kB; lsn=0/1A26A38, redo lsn=0/1A26A00
2025-04-23 11:33:36.918 CDT [19660] FATAL:  role "postgres" does not exist
2025-04-23 11:35:38.942 CDT [14668] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2025-04-23 11:36:46.189 CDT [17724] LOG:  checkpoint starting: time
2025-04-23 11:36:47.087 CDT [17724] LOG:  checkpoint complete: wrote 8 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.877 s, sync=0.007 s, total=0.898 s; sync files=3, longest=0.004 s, average=0.003 s; distance=31 kB, estimate=4142 kB; lsn=0/1A2E950, redo lsn=0/1A2E918
2025-04-23 11:40:41.071 CDT [7004] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2025-04-23 11:45:41.693 CDT [4816] ERROR:  syntax error at or near "/" at character 1
2025-04-23 11:45:41.693 CDT [4816] STATEMENT:  /d
	/d service 
	CREATE TABLE IF NOT EXISTS "service" (
	  "service_id" SERIAL PRIMARY KEY,
	  "service_name" VARCHAR(255),
	  "service_description" TEXT,
	  "cost_of_service" INTEGER,
	  "estimated_time" INTEGER
	);
2025-04-23 11:46:46.103 CDT [17724] LOG:  checkpoint starting: time
2025-04-23 11:46:51.688 CDT [17724] LOG:  checkpoint complete: wrote 51 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=5.502 s, sync=0.063 s, total=5.586 s; sync files=42, longest=0.003 s, average=0.002 s; distance=159 kB, estimate=3744 kB; lsn=0/1A56760, redo lsn=0/1A56728
2025-04-23 11:51:46.702 CDT [17724] LOG:  checkpoint starting: time
2025-04-23 11:51:48.150 CDT [17724] LOG:  checkpoint complete: wrote 13 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=1.419 s, sync=0.011 s, total=1.448 s; sync files=8, longest=0.002 s, average=0.002 s; distance=17 kB, estimate=3371 kB; lsn=0/1A5AF20, redo lsn=0/1A5AEE8
2025-04-23 11:56:46.164 CDT [17724] LOG:  checkpoint starting: time
2025-04-23 11:56:46.740 CDT [17724] LOG:  checkpoint complete: wrote 5 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.543 s, sync=0.010 s, total=0.577 s; sync files=4, longest=0.003 s, average=0.003 s; distance=7 kB, estimate=3035 kB; lsn=0/1A5CD30, redo lsn=0/1A5CCF8
2025-04-23 13:12:04.646 CDT [11012] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2025-04-23 13:12:13.323 CDT [21144] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2025-04-23 13:16:46.870 CDT [17724] LOG:  checkpoint starting: time
2025-04-23 13:16:52.945 CDT [17724] LOG:  checkpoint complete: wrote 56 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=6.005 s, sync=0.048 s, total=6.076 s; sync files=49, longest=0.003 s, average=0.001 s; distance=279 kB, estimate=2759 kB; lsn=0/1AA2AD0, redo lsn=0/1AA2A60
2025-04-23 13:21:46.960 CDT [17724] LOG:  checkpoint starting: time
2025-04-23 13:21:47.298 CDT [17724] LOG:  checkpoint complete: wrote 4 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.321 s, sync=0.009 s, total=0.339 s; sync files=4, longest=0.003 s, average=0.003 s; distance=0 kB, estimate=2483 kB; lsn=0/1AA2E20, redo lsn=0/1AA2DE8
2025-04-23 15:06:50.439 CDT [17724] LOG:  checkpoint starting: time
2025-04-23 15:06:51.144 CDT [17724] LOG:  checkpoint complete: wrote 7 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.660 s, sync=0.016 s, total=0.707 s; sync files=7, longest=0.004 s, average=0.003 s; distance=1 kB, estimate=2235 kB; lsn=0/1AA3248, redo lsn=0/1AA3210
2025-04-23 15:26:32.670 CDT [9692] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2025-04-23 15:26:50.161 CDT [17724] LOG:  checkpoint starting: time
2025-04-23 15:26:54.136 CDT [17724] LOG:  checkpoint complete: wrote 37 buffers (0.2%); 0 WAL file(s) added, 0 removed, 0 recycled; write=3.921 s, sync=0.033 s, total=3.976 s; sync files=34, longest=0.003 s, average=0.001 s; distance=166 kB, estimate=2028 kB; lsn=0/1ACCDF8, redo lsn=0/1ACCD88
2025-04-23 15:27:01.046 CDT [2728] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2025-04-23 15:31:50.139 CDT [17724] LOG:  checkpoint starting: time
2025-04-23 15:31:55.657 CDT [17724] LOG:  checkpoint complete: wrote 51 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=5.456 s, sync=0.044 s, total=5.519 s; sync files=40, longest=0.002 s, average=0.002 s; distance=247 kB, estimate=1850 kB; lsn=0/1B0AA90, redo lsn=0/1B0AA58
2025-04-23 15:56:50.692 CDT [17724] LOG:  checkpoint starting: time
2025-04-23 15:56:55.810 CDT [17724] LOG:  checkpoint complete: wrote 47 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=5.025 s, sync=0.059 s, total=5.119 s; sync files=40, longest=0.003 s, average=0.002 s; distance=245 kB, estimate=1689 kB; lsn=0/1B48110, redo lsn=0/1B480D8
2025-04-23 15:59:00.150 CDT [6412] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2025-04-23 15:59:05.490 CDT [22760] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2025-04-23 15:59:14.055 CDT [18868] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2025-04-23 16:01:50.819 CDT [17724] LOG:  checkpoint starting: time
2025-04-23 16:01:58.501 CDT [17724] LOG:  checkpoint complete: wrote 70 buffers (0.4%); 0 WAL file(s) added, 0 removed, 0 recycled; write=7.551 s, sync=0.078 s, total=7.683 s; sync files=69, longest=0.003 s, average=0.002 s; distance=470 kB, estimate=1568 kB; lsn=0/1BBDBA8, redo lsn=0/1BBDB70
2025-04-23 16:06:50.508 CDT [17724] LOG:  checkpoint starting: time
2025-04-23 16:06:54.833 CDT [17724] LOG:  checkpoint complete: wrote 40 buffers (0.2%); 0 WAL file(s) added, 0 removed, 0 recycled; write=4.277 s, sync=0.030 s, total=4.326 s; sync files=38, longest=0.002 s, average=0.001 s; distance=229 kB, estimate=1434 kB; lsn=0/1BF7368, redo lsn=0/1BF7330
2025-04-23 16:08:27.342 CDT [23064] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2025-04-23 16:08:31.120 CDT [16996] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2025-04-23 16:11:50.844 CDT [17724] LOG:  checkpoint starting: time
2025-04-23 16:11:59.956 CDT [17724] LOG:  checkpoint complete: wrote 83 buffers (0.5%); 1 WAL file(s) added, 0 removed, 0 recycled; write=8.923 s, sync=0.050 s, total=9.113 s; sync files=53, longest=0.003 s, average=0.001 s; distance=456 kB, estimate=1336 kB; lsn=0/1C69738, redo lsn=0/1C69700
2025-04-23 16:36:50.992 CDT [17724] LOG:  checkpoint starting: time
2025-04-23 16:36:55.647 CDT [17724] LOG:  checkpoint complete: wrote 43 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=4.598 s, sync=0.048 s, total=4.655 s; sync files=36, longest=0.004 s, average=0.002 s; distance=191 kB, estimate=1221 kB; lsn=0/1C99598, redo lsn=0/1C99560
2025-04-23 16:41:50.655 CDT [17724] LOG:  checkpoint starting: time
2025-04-23 16:41:51.344 CDT [17724] LOG:  checkpoint complete: wrote 7 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.657 s, sync=0.013 s, total=0.690 s; sync files=7, longest=0.003 s, average=0.002 s; distance=0 kB, estimate=1099 kB; lsn=0/1C99888, redo lsn=0/1C99850
2025-04-23 16:56:50.378 CDT [17724] LOG:  checkpoint starting: time
2025-04-23 16:56:54.794 CDT [17724] LOG:  checkpoint complete: wrote 41 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=4.358 s, sync=0.038 s, total=4.417 s; sync files=38, longest=0.002 s, average=0.001 s; distance=229 kB, estimate=1012 kB; lsn=0/1CE27C0, redo lsn=0/1CD2F58
2025-04-23 16:57:12.926 CDT [13824] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2025-04-23 17:01:50.808 CDT [17724] LOG:  checkpoint starting: time
2025-04-23 17:01:58.863 CDT [17724] LOG:  checkpoint complete: wrote 74 buffers (0.5%); 0 WAL file(s) added, 0 removed, 0 recycled; write=7.979 s, sync=0.054 s, total=8.055 s; sync files=45, longest=0.003 s, average=0.002 s; distance=323 kB, estimate=943 kB; lsn=0/1D23B90, redo lsn=0/1D23B58
2025-04-23 19:23:07.045 CDT [17724] LOG:  checkpoint starting: time
2025-04-23 19:23:08.285 CDT [17724] LOG:  checkpoint complete: wrote 12 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=1.204 s, sync=0.011 s, total=1.243 s; sync files=9, longest=0.002 s, average=0.002 s; distance=4 kB, estimate=849 kB; lsn=0/1D24E88, redo lsn=0/1D24E50
2025-04-23 19:28:07.287 CDT [17724] LOG:  checkpoint starting: time
2025-04-23 19:28:07.661 CDT [17724] LOG:  checkpoint complete: wrote 4 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.343 s, sync=0.008 s, total=0.375 s; sync files=4, longest=0.003 s, average=0.002 s; distance=1 kB, estimate=765 kB; lsn=0/1D25308, redo lsn=0/1D252D0
2025-04-23 21:34:56.681 CDT [17724] LOG:  checkpoint starting: time
2025-04-23 21:34:57.060 CDT [17724] LOG:  checkpoint complete: wrote 4 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.338 s, sync=0.012 s, total=0.380 s; sync files=4, longest=0.005 s, average=0.003 s; distance=1 kB, estimate=688 kB; lsn=0/1D257E8, redo lsn=0/1D257B0
2025-04-24 18:09:56.234 CDT [13464] LOG:  server process (PID 20796) was terminated by exception 0xC000013A
2025-04-24 18:09:56.234 CDT [13464] DETAIL:  Failed process was running: 
	        SELECT
	            roles.oid as id, roles.rolname as name,
	            roles.rolsuper as is_superuser,
	            CASE WHEN roles.rolsuper THEN true ELSE roles.rolcreaterole END as
	            can_create_role,
	            CASE WHEN roles.rolsuper THEN true
	            ELSE roles.rolcreatedb END as can_create_db,
	            CASE WHEN 'pg_signal_backend'=ANY(ARRAY(WITH RECURSIVE cte AS (
	            SELECT pg_roles.oid,pg_roles.rolname FROM pg_roles
	                WHERE pg_roles.oid = roles.oid
	            UNION ALL
	            SELECT m.roleid,pgr.rolname FROM cte cte_1
	                JOIN pg_auth_members m ON m.member = cte_1.oid
	                JOIN pg_roles pgr ON pgr.oid = m.roleid)
	            SELECT rolname  FROM cte)) THEN True
	            ELSE False END as can_signal_backend
	        FROM
	            pg_catalog.pg_roles as roles
	        WHERE
	            rolname = current_user
2025-04-24 18:09:56.234 CDT [13464] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2025-04-24 18:09:56.234 CDT [13464] LOG:  terminating any other active server processes
2025-04-24 18:09:56.305 CDT [13464] LOG:  received fast shutdown request
^C